### ISSUE TITLE
Increase default interval based on new "random position in queue" 

### ISSUE THREAD

**Issue by jasonraimondi** [camtheperson/get-my-ps5#55]
We should consider increase the default base interval from `5s` to something like `30s` to `1m` since the new playstation direct queue is putting users in a random position in queue. 

This project is still useful because it will open the page when ready, allowing you to not have to worry about checking twitter or where ever else users are checking in stock notifications.

This will help negate being IP banned.

<img width="714" alt="Screen Shot 2020-12-17 at 3 03 11 PM" src="https://user-images.githubusercontent.com/5787967/102554257-45ba7480-4079-11eb-8ce6-3c1522456824.png">

Edit: my original message and title said "reduce"... totally wrong, it should have been "increase"

**Comment by wibuf** [comment]
You can do this in index.js by editing this line:

`checkForPlaystationDirectRedirect(5000, onSuccess, playstationType[choice].id, await puppeteer.launch());`

To

`checkForPlaystationDirectRedirect(30000, onSuccess, playstationType[choice].id, await puppeteer.launch());`

Make it 60000 if you want a full minute instead of 30 seconds

**Comment by jasonraimondi** [comment]
Thank you for the comment. My thought here is to increase the default timeout and allow users to customize the interval via dotenv. I've added support for this ticket here: 

https://github.com/camtheperson/get-my-ps5/pull/49/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R31
